const arena=document.getElementById("gameArena"),duck=document.getElementById("duckPlayer"),scoreEl=document.getElementById("score"),timeEl=document.getElementById("time"),goalEl=document.getElementById("goal"),msg=document.getElementById("duckMessage"),startBtn=document.getElementById("startDuckGame");
const goal=12;let score=0,timeLeft=30,running=false,x=40,y=150,timer,spawnTimer,animationId;const keys=new Set();
const funny=["QUACK detected.","Bread acquired. Emotional support increased.","Duck has entered silly mode.","Multiverse duck approves.","Professional waddling detected.","Too much duck energy in one timeline.","Duck says: absolutely iconic."];
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}function rect(){return arena.getBoundingClientRect()}function setDuck(){const r=rect();x=clamp(x,0,r.width-72);y=clamp(y,0,r.height-62);duck.style.left=x+"px";duck.style.top=y+"px"}
function overlap(a,b){return !(a.right<b.left||a.left>b.right||a.bottom<b.top||a.top>b.bottom)}
function spawn(){if(!running)return;const r=rect(),bad=Math.random()<.28,item=document.createElement("div");item.className=bad?"hazard":"collectible";item.dataset.type=bad?"hazard":"good";item.textContent=bad?"💧":(Math.random()<.55?"🍞":"❤️");item.style.left=Math.random()*(r.width-46)+"px";item.style.top=Math.random()*(r.height-54)+"px";arena.appendChild(item);setTimeout(()=>item.remove(),bad?4200:5200)}
function confetti(){const r=rect();for(let i=0;i<28;i++){const c=document.createElement("div");c.className="duck-confetti";c.style.left=r.width/2+"px";c.style.top=r.height/2+"px";c.style.background=["#ffd84a","#74d7ff","#ff8bd1","#fff"][i%4];c.style.setProperty("--x",(-160+Math.random()*320)+"px");c.style.setProperty("--y",(-130+Math.random()*260)+"px");arena.appendChild(c);setTimeout(()=>c.remove(),1100)}}
function end(win){running=false;clearInterval(timer);clearInterval(spawnTimer);cancelAnimationFrame(animationId);msg.textContent=win?"Secret universe complete 🦆⚡ Maximum quack achieved.":"Duck ran out of time. The quack portal needs more bread.";startBtn.textContent=win?"Play again 🦆":"Try again 🦆";startBtn.disabled=false;if(win)confetti()}
function update(){if(!running)return;let vx=0,vy=0;if(keys.has("ArrowLeft")||keys.has("a"))vx-=4.2;if(keys.has("ArrowRight")||keys.has("d"))vx+=4.2;if(keys.has("ArrowUp")||keys.has("w"))vy-=4.2;if(keys.has("ArrowDown")||keys.has("s"))vy+=4.2;x+=vx;y+=vy;setDuck();if(vx<0)duck.style.transform="scaleX(-1)";else if(vx>0)duck.style.transform="scaleX(1)";
const dr=duck.getBoundingClientRect();document.querySelectorAll(".collectible,.hazard").forEach(item=>{if(overlap(dr,item.getBoundingClientRect())){const type=item.dataset.type;item.remove();if(type==="good"){score++;scoreEl.textContent=score;msg.textContent=funny[Math.floor(Math.random()*funny.length)];if(score>=goal)end(true)}else{score=Math.max(0,score-2);scoreEl.textContent=score;msg.textContent="Puddle attack. Duck lost bread confidence."}}});animationId=requestAnimationFrame(update)}
function start(){document.querySelectorAll(".collectible,.hazard,.duck-confetti").forEach(e=>e.remove());score=0;timeLeft=30;x=40;y=150;running=true;scoreEl.textContent=score;timeEl.textContent=timeLeft;goalEl.textContent=goal;msg.textContent="Duck portal open. Collect bread and hearts.";startBtn.disabled=true;startBtn.textContent="Duck running...";setDuck();for(let i=0;i<6;i++)setTimeout(spawn,i*300);spawnTimer=setInterval(spawn,720);timer=setInterval(()=>{timeLeft--;timeEl.textContent=timeLeft;if(timeLeft<=0)end(score>=goal)},1000);update()}
window.addEventListener("keydown",e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown","w","a","s","d"].includes(k)){e.preventDefault();keys.add(k)}});window.addEventListener("keyup",e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));window.addEventListener("resize",setDuck);startBtn.addEventListener("click",start);setDuck();